# Use absolute paths instead of relative paths so that sub-projects
# using the 'extends' key can find static assets.
# https://jupyterbook.org/blog/posts/2026/multi-repo
version: 1
site:
  options:
    lang: en
    logo: https://raw.githubusercontent.com/UC-OSPO-Network/ucospo.net/refs/heads/main/static/images/logo.svg
    favicon: https://raw.githubusercontent.com/UC-OSPO-Network/ucospo.net/refs/heads/main/static/images/favicon.ico
    folders: true
    style: https://raw.githubusercontent.com/UC-OSPO-Network/ucospo.net/refs/heads/main/static/css/custom.css
    logo_text: "UC OSPO Network"
    hide_footer_links: true
    internal_domains: ucospo.net
  template: book-theme
  parts:
    footer: footer.md
