version: 1
site:
  options:
    lang: en
    logo: https://raw.githubusercontent.com/UC-OSPO-Network/ucospo.net/refs/heads/main/static/images/logo.svg
    favicon: https://raw.githubusercontent.com/UC-OSPO-Network/ucospo.net/refs/heads/main/static/images/favicon.ico
    folders: true
    style: https://raw.githubusercontent.com/UC-OSPO-Network/ucospo.net/refs/heads/main/static/css/custom.css
    logo_text: "UC OSPO Network"
    hide_footer_links: true
    internal_domains: ucospo.net
  template: book-theme
  parts:
    footer: footer.md
